<div class="margin_remove" id="slider">
	<a class="slider_a_0 slider_a_all" href="javascript:void(0)">
		<img class="slider_img" src="" />
		<div class="slider_content">
			<div class="slider_title">茉莉QQ机器人新版本开发中</div>
			<div class="slider_memo">茉莉QQ机器人4.0版本开发中，敬请期待</div>
			<span class="slider_btn">了解详情</span>
		</div>
	</a>
	<a class="slider_a_1 slider_a_all" href="http://jq.qq.com/?_wv=1027&k=XgIIzg" target="_blank">
		<img class="slider_img" src="" />
		<div class="slider_content">
			<div class="slider_title">欢迎加入茉莉QQ机器人开发群</div>
			<div class="slider_memo">茉莉QQ机器人开发交流群：70941475，请有一定的编程基础才申请进群</div>
			<span class="slider_btn">申请进群</span>
		</div>
	</a>
	<a class="slider_a_2 slider_a_all" href="http://bbs.itpk.cn" target="_blank">
		<img class="slider_img" src="" />
		<div class="slider_content">
			<div class="slider_title">茉莉QQ机器人新版本发布区</div>
			<div class="slider_memo">官方论坛地址http://bbs.itpk.cn</div>
			<span class="slider_btn">点击进入</span>
		</div>
	</a>
	<a class="slider_a_3 slider_a_all" href="javascript:void(0)">
		<img class="slider_img" src="" />
		<div class="slider_content">
			<div class="slider_title">欢迎对开发提出更多的宝贵意见</div>
			<div class="slider_memo">希望能收到大家的开发建议呢，这能帮助我开发出更符合大家胃口的程序</div>
			<span class="slider_btn">发表建议</span>
		</div>
	</a>
	<a class="slider_a_4 slider_a_all" href="javascript:void(0)">
		<img class="slider_img" src="" />
		<div class="slider_content">
			<div class="slider_title">谢谢大家对茉莉QQ机器人的支持</div>
			<div class="slider_memo">谢谢大家的支持，你的支持将化为我们的动力</div>
			<span class="slider_btn">了解详情</span>
		</div>
	</a>
	<div class="slider_nav">
		<i id="i0"></i>
		<i id="i1"></i>
		<i id="i2"></i>
		<i id="i3"></i>
		<i id="i4"></i>
	</div>
</div>
<div class="main_all">
	<div class = "container">
		<div class="con_header">
			<h2>茉莉QQ机器人新版开发中</h2>
		</div>
		<div class="con_content">
			<p>说明文档.......................</p>
			<p>鹅鹅鹅鹅.......................</p>
			<p>哈哈哈哈.......................</p>
		</div>
	</div>
</div>
<div class="main_all">
	<div class = "container">
		<div class="con_header">
			<h2>新版本新体验</h2>
		</div>
		<div class="con_content">
			<p>说明文档.......................</p>
			<p>鹅鹅鹅鹅.......................</p>
			<p>哈哈哈哈.......................</p>
		</div>
	</div>
</div>
<div id="brief">
	<div class = "container">
		<div class = "robot-about about1">
			<p class = "about-ico"><i class = "fa fa-laptop fa-fw"></i></p>
			<p class = "about-title">迅捷查询丶方便实用</p>
			<p class = "about-content">实时查询天气预报、LOL战绩（英雄联盟）、身份证信息、QQ资料、IP等，还能抽签讲笑话</p>
		</div>
		<div class = "robot-about about2">
			<p class = "about-ico"><i class = "fa fa-book fa-fw"></i></p>
			<p class = "about-title">机器人词库多样化</p>
			<p class = "about-content">基于茉莉机器人API插件，能完美胜任各类网站在线客服，能识别和发送QQ表情，聊天不在话下</p>
		</div>
		<div class = "robot-about about3">
			<p class = "about-ico"><i class = "fa fa-dashboard fa-fw"></i></p>
			<p class = "about-title">全面智能丶高速稳定</p>
			<p class = "about-content">基于插件指令，可以智能检测群广告等，后台离线稳定运行，无需看管，是群主必要的得力助手</p>
		</div>
		<div class = "robot-about about4 container-last">
			<p class = "about-ico"><i class = "fa fa-cogs fa-fw"></i></p>
			<p class = "about-title">个性设计丶灵活设置</p>
			<p class = "about-content">提供丰富的设置选项，海量的插件，精准控制机器人的各种举动，打造属于自己的机器人</p>
		</div>
	</div>
</div>