<?php 

/**
 * 公共尾部文件
 * @author 冬天的秘密
 * @link http://bbs.itpk.cn
 * @version 4.0
 */

require_once TEMPLATE_FOLDER . "common/login-form.inc";

?>

<div id="footer">
	<div class="container">
		<p class="ft_big">
			<a href="javascript:void(0)" target="_blank">关于我们</a>
			<a href="javascript:void(0)" target="_blank">法律声明</a>
			<a href="javascript:void(0)" target="_blank">政策法规</a>
			<a href="javascript:void(0)" target="_blank">服务公告</a>
			<a href="javascript:void(0)" target="_blank">友情链接</a>
		</p>
		<p class="ft_link">
			<a href="javascript:void(0)" target="_blank">友情链接1</a>
			<a href="javascript:void(0)" target="_blank">友情链接2</a>
			<a href="javascript:void(0)" target="_blank">友情链接3</a>
			<a href="javascript:void(0)" target="_blank">友情链接4</a>
			<a href="javascript:void(0)" target="_blank">友情链接5</a>
			<a href="javascript:void(0)" target="_blank">友情链接6</a>
			<a href="javascript:void(0)" target="_blank">友情链接7</a>
			<a href="javascript:void(0)" target="_blank">友情链接8</a>
			<a href="javascript:void(0)" target="_blank">友情链接9</a>
			<a href="javascript:void(0)" target="_blank">友情链接10</a>
			<a href="javascript:void(0)" target="_blank">友情链接11</a>
			<a href="javascript:void(0)" target="_blank">友情链接12</a>
			<a href="javascript:void(0)" target="_blank">友情链接13</a>
			<a href="javascript:void(0)" target="_blank">友情链接</a>
			<a href="javascript:void(0)" target="_blank">友情链接</a>
			<a href="javascript:void(0)" target="_blank">友情链接</a>
		</p>
		<p class="ft_copyright">
			&copy; 2015 ITPK.CN 版权所有 ICP证：浙ICP备13031093号
		</p>
	</div>
</div>
<div id="footer_scroll">
	<div class="top_scroll">
		<a href="javascript:(scrollTop());" title="返回顶部"><i class="fa fa-chevron-up fa-fb"></i></a>
	</div>
	<div class="ewm_scroll">
		<a href="javascript:void(0)"><i class="fa fa-qrcode fa-fb"></i></a>
	</div>
	<div class="fot_scroll">
		<a href="javascript:(scrollFot());" title="返回底部"><i class="fa fa-chevron-down fa-fb"></i></a>
	</div>
</div>
<script type="text/javascript" src="http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
<script type="text/javascript" src="http://apps.bdimg.com/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
<script type="text/javascript" src="./template/default/js/main.js"></script>
</body>
</html>